(add-to-list 'load-path "~/.emacs.d/site-lisp")
(setq custom-file "~/.emacs.d/conf/custom.el")
(load custom-file)
(load "~/.emacs.d/conf/theme.el")
(load "~/.emacs.d/conf/compile.el")
(load "~/.emacs.d/conf/auto-complete.el")
(load "~/.emacs.d/conf/yasnippet.el")
(load "~/.emacs.d/conf/dirtree.el")
;; (load "~/.emacs.d/conf/tree.el")
;; (load "~/.emacs.d/conf/helm.el")
