(require 'smart-compile+)
;; (global-set-key (kbd "<f9>") 'smart-compile)
;; (global-set-key (kbd "<C-f9>") 'smart-run)
(defun shrink-compile-window()
  (interactive)
  ;; (select-window (get-buffer-window "*compilation*"))
  (setq compiled_buffer_name (buffer-name (current-buffer)))
  (switch-to-buffer-other-window "*compilation*")
  (if (< (/ (frame-height) 3) (window-height))
      (shrink-window (/ (window-height) 2)))
  (switch-to-buffer-other-window compiled_buffer_name))
(global-set-key (kbd "<f9>") '(lambda()
                                (interactive)
                                (save-some-buffers t)
                                (smart-run)
                                (shrink-compile-window)))
